POST http://localhost:5000/api/v1/category/create
Content-Type: application/json

{
    "name": "Design System",
    "parent": "634e02ebeb301ae1622cd161"
}

###
PUT http://localhost:5000/api/v1/category/info/634d5418245ab9a66f38a9c7
Content-Type: application/json

{
    "name": "Design System",
    "parent": "634e02ebeb301ae1622cd161"
}


###
POST http://localhost:5000/api/v1/wallet/create
Content-Type: application/json

{
    "userId": "122222222"
}